=== MarianMacik/sdk-java/api/src/main/resources/schema/workflow.json
{
  "$id": "https://wg-serverless.org/workflow.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Serverless Workflow is a vendor-neutral specification for defining the model of workflows responsible for orchestrating event-driven serverless applications.",
  "type": "object",
  "extendsJavaClass": "io.serverlessworkflow.api.workflow.BaseWorkflow",
  "javaType": "io.serverlessworkflow.api.Workflow",
  "javaInterfaces": [
    "java.io.Serializable"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Workflow unique identifier",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "Workflow name",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "description": "Workflow description"
    },
    "version": {
      "type": "string",
      "description": "Workflow version"
    },
    "start": {
      "$ref": "start/start.json",
      "description": "Defines workflow start"
    },
    "schemaVersion": {
      "type": "string",
      "description": "Serverless Workflow schema version"
    },
    "expressionLang": {
      "type": "string",
      "description": "Identifies the expression language used for workflow expressions. Default is 'jq'",
      "default": "jq",
      "minLength": 1
    },
    "execTimeout": {
      "description": "Workflow execution timeout",
      "$ref": "exectimeout/exectimeout.json"
    },
    "keepActive": {
      "type": "boolean",
      "default": false,
      "description": "If 'true', workflow instances is not terminated when there are no active execution paths. Instance can be terminated via 'terminate end definition' or reaching defined 'execTimeout'"
    },
    "metadata": {
      "$ref": "metadata/metadata.json"
    },
    "events": {
      "type": "object",
      "existingJavaType": "io.serverlessworkflow.api.workflow.Events",
      "description": "Workflow event definitions"
    },
    "functions": {
      "type": "object",
      "existingJavaType": "io.serverlessworkflow.api.workflow.Functions",
      "description": "Workflow function definitions"
    },
    "retries": {
      "type": "object",
      "existingJavaType": "io.serverlessworkflow.api.workflow.Retries",
      "description": "Workflow retry definitions"
    },
    "states": {
      "type": "array",
      "description": "State Definitions",
      "items": {
        "type": "object",
        "existingJavaType": "io.serverlessworkflow.api.interfaces.State",
        "anyOf": [
          {
            "title": "Delay State",
            "$ref": "states/delaystate.json"
          },
          {
            "title": "Event State",
            "$ref": "states/eventstate.json"
          },
          {
            "title": "Operation State",
            "$ref": "states/operationstate.json"
          },
          {
            "title": "Parallel State",
            "$ref": "states/parallelstate.json"
          },
          {
            "title": "Switch State",
            "$ref": "states/switchstate.json"
          },
          {
            "title": "SubFlow State",
            "$ref": "states/subflowstate.json"
          },
          {
            "title": "Relay State",
            "$ref": "states/injectstate.json"
          },
          {
            "title": "ForEach State",
            "$ref": "states/foreachstate.json"
          },
          {
            "title": "Callback State",
            "$ref": "states/callbackstate.json"
          }
        ]
      }
    },
    "extensions": {
      "type": "array",
      "description": "Workflow Extensions",
      "items": {
        "type": "object",
        "existingJavaType": "io.serverlessworkflow.api.interfaces.Extension"
      }
    }
  },
  "required": [
    "id",
    "name",
    "version",
    "states"
  ]
}

=== MarianMacik/sdk-java/diagram/src/test/resources/examples/singleswitchstate.json
{
  "id": "testSwitch",
  "name": "Test Switch State Workflow",
  "description": "This is a test switch state workflow",
  "version": "1.0",
  "states": [
    {
      "name": "SwitchIt",
      "type": "switch",
      "start": {"kind":"default"},
      "dataConditions": [
        {
          "name": "first",
          "condition": "",
          "transition": {
            "nextState": "FromFirstCondition"
          }
        },
        {
          "name": "second",
          "condition": "",
          "transition": {
            "nextState": "FromSecondCondition"
          }
        },
        {
          "name": "third",
          "condition": "",
          "end": {
            "kind":"default"
          }
        },
        {
          "name": "fourth",
          "condition": "",
          "end": {
            "kind":"default"
          }
        }
      ]
    },
    {
      "name": "FromFirstCondition",
      "type": "delay",
      "timeDelay": "PT2M",
      "end": {"kind":"default"}
    },
    {
      "name": "FromSecondCondition",
      "type": "inject",
      "data": {},
      "end": {"kind":"default"}
    }
  ]
}

=== MarianMacik/sdk-java/diagram/src/test/resources/examples/singleswitchstateeventconditions.json
{
  "id": "testSwitch",
  "name": "Test Switch State Workflow",
  "description": "This is a test switch state workflow",
  "version": "1.0",
  "states": [
    {
      "name": "SwitchIt",
      "type": "switch",
      "start": {"kind":"default"},
      "eventConditions": [
        {
          "name": "first",
          "eventRef": "firstEvent",
          "transition": {
            "nextState": "FromFirstCondition"
          }
        },
        {
          "name": "second",
          "eventRef": "secondEvent",
          "transition": {
            "nextState": "FromSecondCondition"
          }
        },
        {
          "name": "third",
          "eventRef": "thirdEvent",
          "end": {
            "kind":"default"
          }
        },
        {
          "name": "fourth",
          "eventRef": "fourthEvent",
          "end": {
            "kind":"default"
          }
        }
      ]
    },
    {
      "name": "FromFirstCondition",
      "type": "delay",
      "timeDelay": "PT2M",
      "end": {"kind":"default"}
    },
    {
      "name": "FromSecondCondition",
      "type": "inject",
      "data": {},
      "end": {"kind":"default"}
    }
  ]
}

=== MarianMacik/sdk-java/api/src/test/resources/features/functionrefnoparams.json
{
  "id": "functionrefparams",
  "version": "1.0",
  "name": "Function Ref Params Test",
  "states": [
    {
      "name": "AddPluto",
      "type": "operation",
      "start": true,
      "actions": [
        {
          "functionRef": {
            "refName": "addPet"
          }
        },
        {
          "functionRef": "addPet"
        }
      ],
      "end": true
    }
  ]
}

=== MarianMacik/sdk-java/diagram/src/test/resources/examples/parallel.json
{
  "id": "parallelexec",
  "version": "1.0",
  "name": "Parallel Execution Workflow",
  "description": "Executes two branches in parallel",
  "start": "ParallelExec",
  "states":[
    {
      "name": "ParallelExec",
      "type": "parallel",
      "completionType": "allOf",
      "branches": [
        {
          "name": "ShortDelayBranch"
        },
        {
          "name": "LongDelayBranch"
        }
      ],
      "end": true
    }
  ]
}
